### ISSUE TITLE
Make a checklist for doing releases

### ISSUE THREAD

**Issue by Venti-** [ultravideo/kvazaar#155]
Any comments on this?

## Normally
- Accumulate changes merged to master to the release notes of next release. Tag each note with the relevant commits, if it makes sense.
- Release notes should be in relation to the previous release, so don't add fixes for bugs that probably weren't present in the previous release.
- Not every commit needs it's own release note.
- Tag issues that should be fixed soon to the milestone of next release.
- Tag issues that are unlikely to be fixed before next release to the one after that.
- Do we need a "Never / Patches welcome" milestone?

## During release
- Do these on a Linux box
  - [ ] Run ```make docs``` in case it wasn't run when --help was changed.
  - [ ] Check if configure.ac version needs increasing.
  - [ ] Update global.h version and run ```make docs```.
  - [ ] Tag release in format "vX.Y.Z", to ensure we don't accidentally make dist tarbal with wrong version.
  - [ ] Add dist-tarbal to the release.
  - ```git checkout ${version} && ./autogen.sh && ./configure && make dist```
- [ ] Add 64 and 32 bit Windows binaries to the release
  - Include pthreadVC2.dll
  - Include msvcr100.dll for win32pthreads and msvcr120.dll for Kvazaar. They are in:
    - C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\redist
    - C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\redist
- [ ] Check that nothing major is missing from the release notes.
- [ ] Push tag, write name of tag in release draft ensuring it already exists, press "Publish Release".

## After release
- [ ] Make a draft for next release.
- [ ] Make a new milestone for a release, such that we always have at least the next two releases for tagging issues to milestones.
- [ ] Move issues that aren't going to get fixed in the next release to the one after that.
- [ ] Make a new issue for the release and copy this checklist to it.

**Comment by aryla** [comment]
Before the release, we should run `tools/genmanpage.sh` and `tools/update_readme.sh` and commit any changes to the readme and manpage. Then, after bumping the version, run `tools/genmanpage.sh` again to update the manpage with the new version number.

**Comment by Venti-** [comment]
Ok, added those steps.
